[tool.poetry]
name = "cookiecutter-data-science"
version = "0.1.0"
description = ""
authors = ["NaturalAntibody"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.2.3"
mkdocs-cinder = "^1.2.0"
cookiecutter = "^1.7.3"
pytest = ">=7.2"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
