[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author_name }}"]

include = ["{{ cookiecutter.repo_name }}/py.typed"]

[tool.poetry.dependencies]
python = "^3.9,<3.10"
python-dotenv = ">=0.5.1"

[tool.poetry.dev-dependencies]
pytest = ">=6.2.4"
pylint = ">=2.6.0"
pre-commit = ">=2.7.1"
mypy = ">=0.790"
flake8 = ">=3.8.4"
ipython = ">=7.18.1"
pytest-cov = ">=2.10.1"
setuptools = ">=50.3.2"
autopep8 = ">=1.5.4"
ipyparallel = ">=6.3.0"
pytest-icdiff = ">=0.5"
rope = ">=0.18.0"
python-semantic-release = ">=7.3.0"
commitizen = ">=2.6.0"
coverage = ">=5.5"
Sphinx = ">=4.1.2"
awscli = ">=1.20.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "{{ cookiecutter.repo_name }}/__init__.py:__version__",
    "pyproject.toml:version"
]
upload_to_pypi = false
commit_version_number = true
changelog_file = "CHANGELOG.md"
hvcs = "github"
build_command = "poetry build"
commit_subject = "bump: {version} [skip ci]"

[tool.commitizen]
name = "cz_conventional_commits"

[tool.isort]
profile = "black"
