[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author_name }}"]

include = ["{{ cookiecutter.repo_name }}/py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = ">=0.21.0"

[tool.poetry.dev-dependencies]
pylint = ">=2.10.0"
python-dotenv = ">=0.21.0"
pytest = ">=7.2"
pre-commit = ">=2.20.0"
mypy = ">=0.982"
flake8 = ">=5.0.4"
pytest-cov = ">=4.0.0"
setuptools = ">=65.3.0"
autopep8 = ">=2.0.0"
pytest-icdiff = ">=0.6"
rope = ">=1.4.0"
python-semantic-release = ">=7.32.2"
commitizen = ">=2.37.0"
coverage = ">=6.5"
Sphinx = ">=5.1.0"
awscli = ">=1.27.0"
click = "^8.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "{{ cookiecutter.repo_name }}/__init__.py:__version__",
    "pyproject.toml:version"
]
upload_to_pypi = false
commit_version_number = true
changelog_file = "CHANGELOG.md"
hvcs = "github"
build_command = "poetry build"
commit_subject = "bump: {version} [skip ci]"

[tool.commitizen]
name = "cz_conventional_commits"

[tool.isort]
profile = "black"
