name: PR flow

on:
  push:
    branches:
      - master
  pull_request:


env:
  python-version: "3.10"
  docker-registry: XXX.dkr.ecr.eu-central-1.amazonaws.com
  aws-region: eu-central-1
  env: prod
  min-test-coverage-percent: 50

{% raw -%}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_TOKEN }}

      # - name: Install necessary system packages
      #   run: sudo apt-get -y install hmmer

      - name: Setup python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.python-version }}
      - run: |
          pip install poetry

      - name: Cache poetry virtualenv
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('**/poetry.lock', '**/.pre-commit-config.yaml') }}

      - name: Add github token to gitconfig for cloning dependencies
        run: |
          git config --global url."https://api:${{ secrets.CHECKOUT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install

      - name: Cleanup token
        run: git config --global --remove-section url."https://api:${{ secrets.CHECKOUT_TOKEN }}@github.com/"

      - name: Lint
        run: |
          poetry run pre-commit run --all-files

      - name: Validate commit messages
        env:
          BASEBRANCH: ${{ github.event.pull_request.head.ref }}
          TARGETBRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          bash .github/workflows/checkCommits.sh origin/${BASEBRANCH} origin/${TARGETBRANCH}
        if: ${{ github.ref != 'refs/heads/master' }}

{%- endraw %}
      - name: Test
        run: |
          OUTPUT=$(poetry run pytest --doctest-modules --junitxml=junit/test-results.xml --cov={{ cookiecutter.repo_name }} --cov-report=xml --cov-report=html --cov-report=term-missing)
          CODE=$?
          echo "$OUTPUT" > pytest-output.txt
          echo "$OUTPUT"
          exit $CODE
{% raw %}
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ env.python-version }}
          path: |
            pytest-output.txt
            junit/test-results.xml
            coverage.xml
            htmlcov/
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-output.txt
          title: Coverage report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          junitxml-path: junit/test-results.xml
        if: ${{ always() }}

      - name: Fail on too low coverage
        if: ${{ github.ref != 'refs/heads/master' }}
        run: poetry run coverage report --fail-under=${{ env.min-test-coverage-percent }}

  release:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          fetch-depth: 0

      # - name: Install necessary system packages
      #   run: sudo apt-get -y install hmmer

      - name: Set up python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.python-version }}
      - run: |
          pip install poetry

      - name: Cache poetry virtualenv
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('**/poetry.lock', '**/.pre-commit-config.yaml') }}

      - name: Add github token to gitconfig for cloning dependencies
        run: |
          git config --global url."https://api:${{ secrets.CHECKOUT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install

      - name: Cleanup token
        run: git config --global --remove-section url."https://api:${{ secrets.CHECKOUT_TOKEN }}@github.com/"

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          poetry run semantic-release publish
{%- endraw %}
